# biome, setting name, prefabs, category, default on, is location, description
# NAMES overrides what a pin is called when the object itself carries no name worth using.

# The wild beehive is not the buildable one and carries nothing but its drop table, so left alone it
# would be called Honey. The rest are objects whose drops say less about them than their own name.
NAMES = {
    "Beehives": "$piece_beehive",
    "Vegvisirs": "$piece_vegvisir",
    "Greydwarf Nests": "Greydwarf Nest",
    "Giant Remains": "Giant Remains",
    "Ash Pots": "Ash Pot",
    "Leviathans": "Leviathan",
}

RULES = [
 ("Meadows", "Beehives", ["Beehive"], "beehive", True, False,
  "Wild beehives, in and around the abandoned houses. Honey and a queen bee."),
 ("Meadows", "Vegvisirs", ["Vegvisir_Eikthyr", "Vegvisir_GDKing", "Vegvisir_Bonemass", "Vegvisir_DragonQueen", "Vegvisir_GoblinKing", "Vegvisir_Fader", "Vegvisir_DNBoss"], "vegvisir", True, False,
  "The runestones that reveal a boss on your map."),
 ("Meadows", "Raspberry Bushes", ["RaspberryBush"], "forage", False, False,
  "Raspberry bushes."),
 ("Meadows", "Flint", ["Pickable_Flint"], "forage", False, False,
  "Flint along the shoreline."),
 ("Meadows", "Mushrooms", ["Pickable_Mushroom"], "forage", False, False,
  "Ordinary mushrooms."),
 ("Meadows", "Dandelions", ["Pickable_Dandelion"], "forage", False, False,
  "Dandelions."),
 ("Meadows", "Boar Runestones", ["Runestone_Boars"], "spawner", False, True,
  "Runestones ringed by boar spawners. A place to farm, not a place to gather."),
 ("Meadows", "Altar of Eikthyr", ["Eikthyrnir"], "boss", False, True,
  "Where Eikthyr is summoned. Off by default: use a vegvisir and the game pins it for you."),

 ("BlackForest", "Vegvisirs", ["Vegvisir_Eikthyr", "Vegvisir_GDKing", "Vegvisir_Bonemass", "Vegvisir_DragonQueen", "Vegvisir_GoblinKing", "Vegvisir_Fader", "Vegvisir_DNBoss"], "vegvisir", True, False,
  "The runestones that reveal a boss on your map. Pinned wherever they stand, rather than the ruin around them."),
 ("BlackForest", "Copper Deposits", ["rock4_copper"], "ore", True, False,
  "The large half buried rocks you mine for copper."),
 ("BlackForest", "Tin Deposits", ["MineRock_Tin"], "ore", True, False,
  "Tin along the water's edge."),
 ("BlackForest", "Beehives", ["Beehive"], "beehive", True, False,
  "Wild beehives in the abandoned houses."),
 ("BlackForest", "Blueberry Bushes", ["BlueberryBush"], "forage", False, False,
  "Blueberry bushes. Common enough that pinning them fills the map quickly."),
 ("BlackForest", "Thistle", ["Pickable_Thistle"], "forage", False, False,
  "Thistle, which glows at night and is easier to spot than to pin."),
 ("BlackForest", "Carrot Seeds", ["Pickable_SeedCarrot"], "forage", True, False,
  "Wild carrot seeds. Rare, and the only way to start a carrot farm."),
 ("BlackForest", "Greydwarf Nests", ["Spawner_GreydwarfNest"], "spawner", False, False,
  "The nests that keep sending greydwarfs at you. Break one for an ancient seed."),
 ("BlackForest", "Greydwarf Runestones", ["Runestone_Greydwarfs"], "spawner", False, True,
  "Runestones ringed by greydwarf spawners."),
 ("BlackForest", "Burial Chambers", ["Crypt2", "Crypt3", "Crypt4"], "dungeon", True, True,
  "The entrances to burial chambers, where the surtling cores are."),
 ("BlackForest", "Troll Caves", ["TrollCave02"], "dungeon", True, True,
  "Troll cave entrances."),
 ("BlackForest", "Bear Caves", ["BearCave"], "dungeon", True, True,
  "Bear cave entrances."),
 ("BlackForest", "Mushrooms", ["Pickable_Mushroom"], "forage", False, False,
  "Ordinary mushrooms."),
 ("BlackForest", "Altar of the Elder", ["GDKing"], "boss", False, True,
  "Where the Elder is summoned. Off by default: use a vegvisir and the game pins it for you."),

 ("Swamp", "Vegvisirs", ["Vegvisir_Eikthyr", "Vegvisir_GDKing", "Vegvisir_Bonemass", "Vegvisir_DragonQueen", "Vegvisir_GoblinKing", "Vegvisir_Fader", "Vegvisir_DNBoss"], "vegvisir", True, False,
  "The runestones that reveal a boss on your map."),
 ("Swamp", "Turnip Seeds", ["Pickable_SeedTurnip"], "forage", True, False,
  "Wild turnip seeds. Rare, and the only way to start a turnip farm."),
 ("Swamp", "Thistle", ["Pickable_Thistle"], "forage", False, False,
  "Thistle."),
 ("Swamp", "Sunken Crypts", ["SunkenCrypt4"], "dungeon", True, True,
  "The iron doors into the sunken crypts, where the iron scrap is."),
 ("Swamp", "Muddy Scrap Piles", ["mudpile_beacon"], "ore", False, False,
  "The mud piles you dig for iron scrap. Only inside the crypts, so rarely worth a pin."),
 ("Swamp", "Surtling Fire Holes", ["FireHole"], "spawner", False, True,
  "The burning holes that keep producing surtlings."),
 ("Swamp", "Draugr Runestones", ["Runestone_Draugr"], "spawner", False, True,
  "Runestones ringed by draugr spawners."),
 ("Swamp", "Mushrooms", ["Pickable_Mushroom"], "forage", False, False,
  "Ordinary mushrooms."),
 ("Swamp", "Altar of Bonemass", ["Bonemass"], "boss", False, True,
  "Where Bonemass is summoned. Off by default: use a vegvisir and the game pins it for you."),

 ("Mountain", "Vegvisirs", ["Vegvisir_Eikthyr", "Vegvisir_GDKing", "Vegvisir_Bonemass", "Vegvisir_DragonQueen", "Vegvisir_GoblinKing", "Vegvisir_Fader", "Vegvisir_DNBoss"], "vegvisir", True, False,
  "The runestones that reveal a boss on your map."),
 ("Mountain", "Silver Deposits", ["silvervein"], "ore", True, False,
  "Silver under the snow. Buried, so a pin is worth more here than anywhere else."),
 ("Mountain", "Obsidian Deposits", ["MineRock_Obsidian"], "ore", True, False,
  "The black spires you mine for obsidian."),
 ("Mountain", "Drake Nests", ["DrakeNest01"], "forage", True, True,
  "The nests on the peaks, each holding a dragon egg."),
 ("Mountain", "Altar of Moder", ["Dragonqueen"], "boss", False, True,
  "Where Moder is summoned. Off by default: use a vegvisir and the game pins it for you."),

 ("Plains", "Vegvisirs", ["Vegvisir_Eikthyr", "Vegvisir_GDKing", "Vegvisir_Bonemass", "Vegvisir_DragonQueen", "Vegvisir_GoblinKing", "Vegvisir_Fader", "Vegvisir_DNBoss"], "vegvisir", True, False,
  "The runestones that reveal a boss on your map."),
 ("Plains", "Tar Pits", ["TarPit1", "TarPit1_1", "TarPit2", "TarPit2_1", "TarPit3", "TarPit3_1"], "tar", True, True,
  "The black pools, with growths to pick and a nest of tar blobs guarding them."),
 ("Plains", "Fuling Totems", ["goblin_totempole"], "loot", True, False,
  "The totem in a fuling village, and the only way to summon Yagluth. Pinned instead of the village around it."),
 ("Plains", "Cloudberry Bushes", ["CloudberryBush"], "forage", False, False,
  "Cloudberry bushes."),
 ("Plains", "Altar of Yagluth", ["GoblinKing"], "boss", False, True,
  "Where Yagluth is summoned. Off by default: use a vegvisir and the game pins it for you."),

 ("Mistlands", "Yggdrasil Roots", ["YggdrasilRoot"], "sap", True, False,
  "The hanging roots you tap for sap."),
 ("Mistlands", "Giant Remains", ["giant_ribs", "giant_helmet1", "giant_helmet2", "giant_sword1", "giant_sword2"], "ore", True, False,
  "The bones and armour of the fallen giants. Black marble, and iron and copper scrap."),
 ("Mistlands", "Magecap", ["Pickable_Mushroom_Magecap"], "forage", False, False,
  "The blue glowing mushrooms, for eitr."),
 ("Mistlands", "Jotun Puffs", ["Pickable_Mushroom_JotunPuffs"], "forage", True, False,
  "The pale puffball mushrooms, for eitr."),
 ("Mistlands", "Entrance to the Queen", ["Mistlands_DvergrBossEntrance1"], "dungeon", True, True,
  "The way into the infested mine where the Queen waits."),
 ("Mistlands", "Dvergr Needle Crates", ["dvergrprops_crate_long"], "loot", True, False,
  "The long crate holding a dvergr needle, which is what a sap extractor is built from. One stands in each guard tower, excavation, harbour and lighthouse."),
 ("Mistlands", "Dvergr Excavations", ["Mistlands_Excavation1", "Mistlands_Excavation2", "Mistlands_Excavation3"], "loot", True, True,
  "Dvergr dig sites, with crates to break and dvergr who mind you breaking them."),

 ("AshLands", "Vegvisirs", ["Vegvisir_Eikthyr", "Vegvisir_GDKing", "Vegvisir_Bonemass", "Vegvisir_DragonQueen", "Vegvisir_GoblinKing", "Vegvisir_Fader", "Vegvisir_DNBoss"], "vegvisir", True, False,
  "The runestones that reveal a boss on your map."),
 ("AshLands", "Flametal", ["LeviathanLava"], "ore", True, False,
  "The flametal in the lava lakes."),
 ("AshLands", "Sulfur Arches", ["SulfurArch"], "ore", True, True,
  "The yellow arches you pick for sulfur stone."),
 ("AshLands", "Unstable Lava Rock", ["UnstableLavaRock"], "ore", True, False,
  "The cracked rocks holding proustite powder."),
 ("AshLands", "Vineberries", ["VineAsh"], "forage", True, False,
  "The vines in the charred ruins. Vineberries, which can be replanted."),
 ("AshLands", "Smoke Puffs", ["Pickable_SmokePuff"], "forage", False, False,
  "The smoking mushrooms."),
 ("AshLands", "Ash Pots", ["ashland_pot2_red"], "loot", True, False,
  "The red clay pots, which break open for bronze and iron."),
 ("AshLands", "Places of Mystery", ["PlaceofMystery1", "PlaceofMystery2", "PlaceofMystery3"], "loot", True, True,
  "Where the pieces of Dyrnwyn are. Three in the world, and no way to finish the sword without them."),
 ("AshLands", "Charred Fortresses", ["CharredFortress"], "dungeon", True, True,
  "The fortresses, holding a molten core, a bell fragment and a great many charred."),
 ("AshLands", "Charred Skulls", ["Pickable_Charredskull"], "forage", False, False,
  "Skulls on the ground, picked for charred skull."),
 ("AshLands", "Volture Nests", ["VoltureNest"], "loot", False, True,
  "Volture nests, built on asksvin carrion worth picking over."),
 ("AshLands", "Charred Tower Ruins", ["CharredTowerRuins1"], "loot", False, True,
  "Ruined towers with pots and fiddlehead."),
 ("AshLands", "Charred Spawner Towers", ["CharredTowerRuins3"], "spawner", False, True,
  "Ruined towers built around a charred spawner."),
 ("AshLands", "Dvergr Town", ["CharredTowerRuins1_dvergr"], "loot", False, True,
  "The dvergr settlements out on the ash sea."),
 ("AshLands", "Altar of Fader", ["FaderLocation"], "boss", False, True,
  "Where Fader is summoned. Off by default: use a vegvisir and the game pins it for you."),

 ("DeepNorth", "Vegvisirs", ["Vegvisir_Eikthyr", "Vegvisir_GDKing", "Vegvisir_Bonemass", "Vegvisir_DragonQueen", "Vegvisir_GoblinKing", "Vegvisir_Fader", "Vegvisir_DNBoss"], "vegvisir", True, False,
  "The runestones that reveal a boss on your map."),
 ("DeepNorth", "Frozen Trolls", ["DN_gammeltrollFrac01", "DN_gammeltrollFrac02"], "ore", True, True,
  "The trolls frozen into the ice, mined for gold ore. Needs a black metal pickaxe."),
 ("DeepNorth", "Morkhalla", ["MorkBorg"], "dungeon", True, True,
  "The black keeps, holding the ancient gemstones."),
 ("DeepNorth", "Memorial Places", ["NorthMemorialPlace"], "loot", True, True,
  "Eleven chests around a runestone and an offering bowl."),
 ("DeepNorth", "Kale Seeds", ["Pickable_SeedKale"], "forage", True, False,
  "Wild kale seeds. Rare, and the only way to start a kale farm."),
 ("DeepNorth", "Lingonberry Bushes", ["LingonberryBush"], "forage", False, False,
  "Lingonberry bushes."),
 ("DeepNorth", "Snowballs", ["Pickable_Snowball"], "forage", False, False,
  "Snowballs."),
 ("DeepNorth", "The Hole", ["TheHole01"], "loot", False, True,
  "A camp built around a hole in the ice, with real goods in it."),

 ("Ocean", "Leviathans", ["Leviathan"], "ore", True, False,
  "The sleeping leviathans, mined for chitin. They dive once you start."),
]
